runtime: python39  # You can change this based on your Python version
entrypoint: uvicorn app.main:app --host=0.0.0.0 --port $PORT

instance_class: F2  # Set instance class according to your resource needs

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
  - url: /.*
    script: auto