runtime: python39

handlers:
  - url: /.*
    script: auto

instance_class: F2  # Adjust this based on your app's resource needs

env_variables:
  FIREBASE_CREDENTIALS: "app/secrets/firebase_credentials.json"
  REDIS_HOST: "10.52.199.70"
  REDIS_PORT: "6379"