version: '3'

services:
  fastapi-backend:
    build: .
    container_name: shift_scall_backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - .:/app
  #   depends_on:
  #     - redis

  # redis:
  #   image: "redis:alpine"
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
