name: Deploy to Google App Engine

on:
  push:
    tags:
      - '*'  # Trigger the workflow on new tags

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-gcp-project-id  # Replace with your GCP project ID
        install_components: app-engine-python  # Add additional components if needed

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Ensure this secret is correctly set up in GitHub Secrets

    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet
