name: Deploy to Google App Engine

on:
  push:
    tags:
      - '*'  # Triggers the workflow when a new tag is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up the Google Cloud SDK without handling authentication here
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: sunny-diorama-435404-g9  # Replace with your actual GCP project ID
        install_components: app-engine-python,app-engine-nodejs  # Specify any components required by your app

    # Authenticate using Google Cloud SDK with the service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Correctly reference your service account JSON key stored in GitHub Secrets

    # Deploy the application to Google App Engine
    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet
