name: Deploy to Google App Engine

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: sunny-diorama-435404-g9
        install_components: app-engine-python

    # Authenticate using Google Cloud SDK with the service account key
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Reference your service account JSON key stored in GitHub Secrets

    # Deploy the application to Google App Engine
    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet
