name: Deploy to Google App Engine

on:
  push:
    tags:
      - '*' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-gcp-project-id  # Replace with your GCP project ID
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # Ensure this secret is correctly set up in GitHub

    - name: Authenticate Docker with Google Cloud
      run: gcloud auth configure-docker

    - name: Deploy to Google App Engine
      run: |
        gcloud config set project your-gcp-project-id  # Ensure this is set to your project ID
        gcloud app deploy --quiet
