name: Deploy to Google App Engine

on:
  push:
    tags:
      - '*'  # Trigger the workflow on new tags

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-gcp-project-id  # Replace with your GCP project ID
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}  # This should reference the correct secret

    - name: Authenticate Google Cloud CLI
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: echo "$SERVICE_ACCOUNT_KEY" | gcloud auth activate-service-account --key-file=-

    - name: Set GCP Project
      run: gcloud config set project your-gcp-project-id  # Replace with your project ID

    - name: Deploy to Google App Engine
      run: gcloud app deploy --quiet
